name: flutter_marvel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  dio: ^5.0.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          style: normal
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
    - family: Gilroy-Heavy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
